Make selector accept array values
deployphp/deployer pull request #2446
Opened 2021-03-06 17:14 UTC by ostrolucky

- [x] Bug fix https://github.com/deployphp/deployer/issues/2445
- [ ] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [x] Tests added?
- [ ] Changelog updated?

      Please, update CHANGELOG.md by running next command:
      $ php bin/changelog

2021-03-06 18:21 UTC, antonmedv requested changes

2021-03-06 18:21 UTC, antonmedv commented on test/joy/DeployTest.php
> +            'deploy:invoke',
Better to create separate test for it. As normal deploy test is also needed. Or even better - unit test for this part of the code.

2021-03-07 08:20 UTC, antonmedv approved these changes

2021-03-07 08:20 UTC, merged

2021-03-08 10:06 UTC, ostrolucky commented
Thanks for quick merge. Can we have new beta release soon? 🙏