Sentry fix for new update_code strategies
deployphp/deployer pull request #2779
Opened 2021-11-23 10:20 UTC by dpfaffenbauer

- [x] Bug fix #…?

Sentry does not work properly with the new `update_code_strategy`, this fixes it to work with both

2021-11-28 23:46 UTC, DamienHarper requested changes

2021-11-28 23:46 UTC, DamienHarper commented on contrib/sentry.php
>          cd('{{release_path}}');
Same here, you'd better `cd('{{deploy_path}}/.dep/repo');` instead to be able to run custom git command with our having to rely on `update_code_strategy => 'clone'`

2021-11-28 23:46 UTC, DamienHarper commented on contrib/sentry.php
> +            cd('{{release_path}}');
You'd better cd('{{deploy_path}}/.dep/repo'); instead to be able to run custom git command with our having to rely on update_code_strategy => 'clone'

2021-11-28 23:59 UTC, DamienHarper requested changes

2021-11-28 23:59 UTC, DamienHarper commented on contrib/sentry.php
> +            return run('cat {{release_path}}/REVISION');
if a custom `git_version_command` has been provided, you'd better `cd('{{deploy_path}}/.dep/repo');` then run the custom `git_version_command` instead.

2021-11-28 23:59 UTC, DamienHarper commented on contrib/sentry.php
> +            return run('cat {{current_path}}/REVISION');
Same here, if a custom `git_version_command` has been provided, you'd better `cd('{{deploy_path}}/.dep/repo');` then run the custom `git_version_command` instead.

2021-11-29 08:25 UTC, antonmedv commented
Why not use REVISION file in all cases?

2021-11-29 09:16 UTC, DamienHarper commented
@antonmedv because I don't want only a commit hash as a version identifier. I used to use `git describe --tags --abbrev=0 2> /dev/null || git log -n 1 --format="%h"` as a custom `git_version_command` to get either the latest tag in the branch or the latest commit hash

2021-11-29 09:54 UTC, antonmedv commented
I see. Can someone also take a look at this pr? Or I!m going to merge it.

2021-11-29 09:58 UTC, DamienHarper commented
@dpfaffenbauer Would you mind to integrate requested changes?

2021-11-29 11:31 UTC, dpfaffenbauer commented
@DamienHarper sure

2021-11-29 11:59 UTC, merged

2021-11-29 12:01 UTC, dpfaffenbauer commented
@antonmedv so should I create a new PR for requested changes?

2021-11-29 12:02 UTC, antonmedv commented
Let’s do separate PR.

2021-11-29 13:22 UTC, DamienHarper commented
@antonmedv @dpfaffenbauer I made a PR for this: https://github.com/deployphp/deployer/pull/2793